name: nsg_controls
description: Set of widgets to use with nsg_data package
# version: 0.2.0
homepage: https://github.com/zenalex/nsg_controls.git
# publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.0.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  get: ^5.0.0-release-candidate-9.2.1
  # get:
  #   path:
  #     ../getx
  nsg_data: #^0.2.0
    path: ../nsg_data
  flutter_fadein: ^2.0.0
  pull_to_refresh: #^2.0.0
    git: https://github.com/ymback/flutter_pulltorefresh.git
  jiffy: ^6.0.0
  flutter_svg: ^2.0.1
  # flutter_calendar_carousel: ^2.1.0
  share_plus: ^10.0.0
  #flutter_slidable:
  #  git:
  #    url: "https://github.com/letsar/flutter_slidable"
  flutter_slidable: ^4.0.0
  another_flushbar: ^1.12.30
  linked_scroll_controller: ^0.2.0
  mask_text_input_formatter: ^2.9.0
  responsive_grid: ^2.1.0
  photo_view: ^0.15.0
  reorderables: ^0.6.0
  package_info_plus: ^8.0.1
  vector_math: ^2.1.2
  flutter_multi_formatter: ^2.13.7
  dotted_line: ^3.1.0
  event: ^2.0.5
  hovering: ^1.0.4
  image: ^4.0.6
  timeago: ^3.7.0

  # to controls!!!
  universal_html: ^2.2.3
  image_picker: ^1.0.2
  image_picker_windows: ^0.2.1
  file_selector: ^1.0.1
  file_selector_windows: ^0.9.3+1
  file_selector_linux: ^0.9.0+1
  image_picker_for_web: ^3.0.1
  file_selector_macos: ^0.9.2
  #эта версия необходима для flutter 3.27 для Android
  file_picker: ^8.1.4
  path: ^1.8.1
  path_provider: ^2.0.14

  syncfusion_flutter_pdfviewer: ^27.2.5
  #adaptive_scrollbar: ^2.1.2
  video_player_win: ^3.1.1
  video_player: ^2.6.0
  url_launcher: ^6.1.10
  crop_your_image: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: NsgIcons
      fonts:
        - asset: fonts/NsgIcons.ttf
