name: nsg_controls
description: A comprehensive set of UI components for rapid application development with nsg_data package. Includes forms, tables, dialogs, file pickers, and more.
version: 1.0.0-beta.1
homepage: https://github.com/zenalex/nsg_controls.git
repository: https://github.com/zenalex/nsg_controls.git
issue_tracker: https://github.com/zenalex/nsg_controls/issues
documentation: https://github.com/zenalex/nsg_controls#readme
publish_to: 'none'

environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  get: ^5.0.0-release-candidate-9.2.1

  # nsg_data: ^1.0.0
  nsg_data: #^0.2.0
    path: ../nsg_data
  flutter_fadein: ^2.0.0
  pull_to_refresh_flutter3: ^2.0.2
  # pull_to_refresh: #^2.0.0
  #   git: https://github.com/ymback/flutter_pulltorefresh.git
  jiffy: ^6.0.0
  flutter_svg: ^2.0.1
  share_plus: ^10.0.0

  flutter_slidable: ^4.0.0
  another_flushbar: ^1.12.30
  linked_scroll_controller: ^0.2.0
  mask_text_input_formatter: ^2.9.0
  responsive_grid: ^2.1.0
  photo_view: ^0.15.0
  reorderables: ^0.6.0
  package_info_plus: ^8.0.1
  vector_math: ^2.1.2
  flutter_multi_formatter: ^2.13.10
  dotted_line: ^3.1.0
  event: ^2.0.5
  hovering: ^1.0.4
  image: ^4.0.6
  timeago: ^3.7.0

  # to controls!!!
  universal_html: ^2.2.3
  image_picker: ^1.0.2
  image_picker_windows: ^0.2.1
  file_selector: ^1.0.1
  file_selector_windows: ^0.9.3+1
  file_selector_linux: ^0.9.0+1
  image_picker_for_web: ^3.0.1
  file_selector_macos: ^0.9.2
  #эта версия необходима для flutter 3.27 для Android
  file_picker: ^8.1.4
  path: ^1.8.1
  path_provider: ^2.0.14

  syncfusion_flutter_pdfviewer: ^29.2.9
  video_player_win: ^3.1.1
  video_player: ^2.6.0
  url_launcher: ^6.1.10
  crop_your_image: ^1.1.0
  dio: ^5.4.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: NsgIcons
      fonts:
        - asset: fonts/NsgIcons.ttf
