name: nsg_controls
description: Set of widgets to use with nsg_data package
#version: 0.3.0
homepage: https://github.com/zenalex/nsg_controls.git
# publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  get: ^5.0.0-beta.52
  go_router: ^6.5.7
  # get:
  #   path: 
  #     ../getx
  nsg_data: #^0.2.0
    path: 
      ../nsg_data
  flutter_fadein: ^2.0.0
  pull_to_refresh: #^2.0.0
    git:
      https://github.com/ymback/flutter_pulltorefresh.git
  jiffy: ^5.0.0 
  flutter_svg: ^2.0.1
  flutter_calendar_carousel: ^2.1.0
  share_plus: ^4.0.4
  flutter_slidable: ^2.0.0
  another_flushbar: ^1.10.29
  linked_scroll_controller: ^0.2.0
  mask_text_input_formatter: ^2.3.0
  image_picker: ^0.8.5+3
  image_picker_windows: ^0.1.0
  file_selector: ^0.8.2+1
  file_selector_windows: ^0.8.2
  file_selector_linux: ^0.9.0+1
  image_picker_for_web: ^2.1.8
  file_picker: ^5.0.1
  responsive_grid: ^2.1.0
  photo_view: ^0.14.0
  reorderables: ^0.5.0
  package_info_plus: ^1.4.3+1
  vector_math: ^2.1.2
  path: ^1.8.1
  flutter_multi_formatter: ^2.6.2
  dotted_line: ^3.1.0
  event: ^2.0.5
  hovering: ^1.0.4
  syncfusion_flutter_pdfviewer: ^20.4.51
  #adaptive_scrollbar: ^2.1.2
  video_player_win: ^2.2.2
  video_player: ^2.6.1
  url_launcher: ^6.1.10
  crop_your_image: ^0.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  

flutter:
  fonts:
    - family:  NsgIcons
      fonts:
       - asset: fonts/NsgIcons.ttf

