name: cached_network_image_web
description: Web implementation of CachedNetworkImage
publish_to: none
version: 1.3.1
homepage: https://github.com/Baseflow/flutter_cached_network_image

environment:
  sdk: ^3.0.0
  flutter: '>=3.10.0'

dependencies:
  cached_network_image_platform_interface: 
    path: ../cached_network_image_platform_interface
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  web: ^1.0.0

dev_dependencies:
  file: '>=7.0.0 <8.0.0'
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
