import 'package:flutter/widgets.dart';

class NsgIcons {
  NsgIcons._();

  static const _kFontFam = 'NsgIcons';
  static const String? _kFontPkg = null;

  /// <i class="nsg-icons md-36">eye_crossed</i> &#x2014; nsg icon named "eye_crossed".
  static const IconData eye_crossed = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter_active = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData football_card = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData football_feild = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData increase = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData italic = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kebab = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData log_out = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData numbered = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pass = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person_remove = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData question = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData radio_button = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData redo = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData refresh = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reorder = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData soccer_ball = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData soccer_penalty = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stadium = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData strikethrough = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData task = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData team = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData t_shirt = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData underlined = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData undo = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData work_schedule = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attach = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attention = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData badge = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell_active = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bold = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData box = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData building = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bus_schedule = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_box = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_radio_button = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData code = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData copy = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData decrease = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doc = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dots = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData double_check = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drop = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
