/// Flutter icons NsgIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NsgIcons
///      fonts:
///       - asset: fonts/NsgIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class NsgIcons {
  NsgIcons._();

  static const _kFontFam = 'NsgIcons';
  static const String? _kFontPkg = null;

  static const IconData building = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bus_schedule = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cake = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_box = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_radio_button = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_down = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_left = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_up = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData code = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData copy = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData decrease = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doc = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dots = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData double_check = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drop = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_crossed = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favorite_filled = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favorite_hollow = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter_active = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData football_card = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forum = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData football_feild = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gallery = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData increase = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData italic = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kebab = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData laurel = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData log_out = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData meatball = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moisture = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData news = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData numbered = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pass = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person_remove = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData question = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData redo = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData radio_button = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData refresh = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reorder = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData route = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData soccer_penalty = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData soccer_ball = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_order_down = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_order_up = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stadium = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData statistics = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData strikethrough = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stethoscope = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData task = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData t_shirt = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData temperature = IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData team = IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thin_up = IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData undo = IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData work_schedule = IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add = IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData underlined = IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData walk_right = IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attach = IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell = IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attention = IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData badge = IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell_active = IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bold = IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData box = IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData absent = IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData select_list = IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
