name: cached_network_image_platform_interface
description: Platform interface for CachedNetworkImage
version: 4.1.1
publish_to: none
homepage: https://github.com/Baseflow/flutter_cached_network_image

environment:
  sdk: ^3.0.0
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  nsg_data:
    path: ../../nsg_data

dev_dependencies:
  file: '>=7.0.0 <8.0.0'
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
